### ISSUE TITLE
Add possibility of changing the path of wp-content

### ISSUE THREAD

**Issue by cristoj** [xfiveco/generator-chisel#336]
if I change the chisel structure, for example:

"wp/any_name_folder/wp-content" for security  reassons, when I run 'yo chisel:page "Page Name"' only generate in wp database the page but not create the page-name.twig file.

```
D:\wamp64\www\my_web\wp>yo chisel:page "Page Name"

Just found a `.yo-rc.json` in a parent directory.
Setting the project root at: D:\wamp64\www\my_web
Success: Created post 219.

assert.js:81
  throw new assert.AssertionError({
  ^
AssertionError: Trying to copy from a source that does not exist: D:\wamp64\www\my_web\wp\wp-content\themes\my_web\templates\page.twig
    at EditionInterface.exports.copy (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\mem-fs-editor\lib\actions\copy.js:47:3)
    at EditionInterface.module.exports [as copyTpl] (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\mem-fs-editor\lib\actions\copy-tpl.js:10:8)
    at async.waterfall (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\generators\page\index.js:121:17)
    at nextTask (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:5317:9)
    at C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:958:16
    at async.waterfall (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\generators\page\index.js:114:9)
    at nextTask (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:5317:9)
    at C:\Users\crist\AppData\Roaming\npm\node_modules\generator-chisel\node_modules\async\dist\async.js:958:16

**Comment by luboskmetko** [comment]
Hi @cristoj can you try to change `dest.wordpress` at line 35 in `package.json` to the folder where your `wp-content` is, eg. 

```
    "dest": {
      "wordpress": "wp/any_name_folder",
```

Let us know if it helps. Thanks

**Comment by cristoj** [comment]
Perfect works fine!!!!
