### ISSUE TITLE
Problem when running existing project (Couldn't open vendor.json)

### ISSUE THREAD

**Issue by kieryk123** [xfiveco/generator-chisel#463]
Hi, I have following error when I try to run `gulp` command.
```
[18:32:16] Using gulpfile ~/projects/xxx/app/gulpfile.js
[18:32:16] Starting 'styles-watch'...
[18:32:16] Starting 'assets-watch'...
[18:32:16] Starting 'vendor-watch'...
[18:32:16] 'vendor-watch' errored after 608 μs
[18:32:16] Error: Couldn't open vendor.json. Please make sure it's present in your /src/scripts directory!
    at getFileList (/Users/pawelkieryk/projects/xxx/app/gulp/tasks/vendor.js:66:13)
    at Gulp.gulp.task (/Users/pawelkieryk/projects/xxx/app/gulp/tasks/vendor.js:90:22)
    at module.exports (/Users/pawelkieryk/projects/xxx/app/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/pawelkieryk/projects/xxx/app/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/pawelkieryk/projects/xxx/app/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/pawelkieryk/projects/xxx/app/node_modules/orchestrator/index.js:134:8)
    at /Users/pawelkieryk/projects/xxx/app/node_modules/gulp-cli/lib/versioned/^3.7.0/index.js:54:20
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
    at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:56:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
[18:32:16] Finished 'styles-watch' after 441 ms
[18:32:16] Finished 'assets-watch' after 18 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxx@0.0.1 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xxx@0.0.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pawelkieryk/.npm/_logs/2020-04-30T16_32_16_741Z-debug.log
```
Could anyone help me? I've tried running on node v11 and v12.

**Comment by kieryk123** [comment]
I've checked and this file is present in mentioned directory. Inside I have empty array: `[ ]`
